modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/PrettyBeaches/issues"

[[mods]]
modId="prettybeaches"
version="${file.jarVersion}"
displayName="Pretty Beaches"
displayURL="https://mods.twelveiterations.com/mc/prettybeaches"
logoFile="prettybeaches-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adjusts water physics when digging sand near water to prevent ugly.
'''

[[dependencies.prettybeaches]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.prettybeaches]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.prettybeaches]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
