modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/PrettyBeaches/issues"

[[mods]]
modId="prettybeaches"
version="${file.jarVersion}"
displayName="Pretty Beaches"
displayURL="https://blay09.net/mods/prettybeaches"
logoFile="prettybeaches-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adjusts water physics when digging sand near water to prevent ugly.
'''

[[dependencies.prettybeaches]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.prettybeaches]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.prettybeaches]]
    modId="balm"
    mandatory=true
    versionRange="[6.0.0,)"
    ordering="NONE"
    side="BOTH"
